CREATE TABLE User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(30) UNIQUE NOT NULL,
    Password VARCHAR(100) NOT NULL,
    Name VARCHAR(100),
    Email VARCHAR(100) UNIQUE NOT NULL,
    HomeAddress TEXT
);
CREATE TABLE CreditCard (
    CardID INT AUTO_INCREMENT PRIMARY KEY,
    CardNumber VARCHAR(16) NOT NULL,
    ExpiryDate DATE NOT NULL,
    CVV VARCHAR(4) NOT NULL,
    Username VARCHAR(30) NOT NULL,
    FOREIGN KEY (Username) REFERENCES User(Username) ON DELETE CASCADE
);