spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: your_db_username
    password: your_db_password
  jpa:
    hibernate:
      ddl-auto: update # Or create, create-drop, validate (use cautiously in production)
    show-sql: true # To see the queries Hibernate makes (optional, for development)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect #If spring.jpa.properties.hibernate.dialect does not work use jakarta.persistence.jdbc.url